/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/forms/input-numbers copy.vue')['default']
    DevTool: typeof import('./components/DevTool.vue')['default']
    Form: typeof import("./components/Form.vue")["default"]
    Input: typeof import('./components/forms/input.vue')['default']
    InputNumbers: typeof import('./components/forms/input-numbers.vue')['default']
    Label: typeof import('./components/label.vue')['default']
    Layout: typeof import('./components/layout.vue')['default']
    Logs: typeof import("./components/logs.vue")["default"]
    NA: typeof import('naive-ui')['NA']
    NAlert: typeof import('naive-ui')['NAlert']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBlockquote: typeof import('naive-ui')['NBlockquote']
    NButton: typeof import('naive-ui')['NButton']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEllipsis: typeof import("naive-ui")["NEllipsis"]
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NFormItemLabel: typeof import("naive-ui")["NFormItemLabel"]
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH1: typeof import("naive-ui")["NH1"]
    NH2: typeof import('naive-ui')['NH2']
    NH3: typeof import('naive-ui')['NH3']
    NH4: typeof import('naive-ui')['NH4']
    NIcon: typeof import('naive-ui')['NIcon']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPopover: typeof import('naive-ui')['NPopover']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NThing: typeof import('naive-ui')['NThing']
    NTooltip: typeof import('naive-ui')['NTooltip']
    Radios: typeof import('./components/forms/radios.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/select.vue')['default']
    Spin: typeof import("./components/spin.vue")["default"]
    Start: typeof import('./components/forms/start.vue')['default']
  }
}
